default:
  image: linaro/wine-arm64

cmd-hello-world:
  script:
    - bash -x ./cmd-hello-world.sh

nodejs-unit-tests:
  script:
    - bash -x ./nodejs-unit-tests.sh

llvm-mingw-linux-x64-hello-world:
  script:
    - bash -x ./llvm-mingw-linux-x64-hello-world.sh

llvm-mingw-windows-arm64-hello-world:
  script:
    - bash -x ./llvm-mingw-windows-arm64-hello-world.sh

msvc-windows-x64-hello-world:
  script:
    - bash -x ./msvc-windows-x64-hello-world.sh

compile-and-run-ninja:
  script:
    - bash -x ./compile-and-run-ninja.sh
