name: wine-arm64

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cmd-hello-world:
    runs-on: ubuntu-latest
    container: pbolinaro/woa-linux
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - run: uname -a
      - run: ls /proc
      - run: ./a.out
      - run: ./qemu-x86_64-static ./a.out
      - run: wine-arm64 --version
      - run: env LD_LIBRARY_PATH=/opt/wine-arm64/usr/lib/aarch64-linux-gnu qemu-aarch64-static /opt/wine-arm64/usr/bin/bash -c '/bin/echo'
      - run: qemu-aarch64-static --version
      - run: bash -x ./job-cmd-hello-world.sh
