name: wine-arm64

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cmd-hello-world:
    runs-on: ubuntu-latest
    container: linaro/wine-arm64
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - run: uname -a
      - run: ls /proc
      - run: ./a.out
      - run: bash -x ./job-cmd-hello-world.sh
